name: CI/CD Docker Only

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main

jobs:
  integration:
    name: Intégration Continue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Lint du code
        run: echo "Linting du dépôt (ajoute flake8 ou autre outil si nécessaire)"

      - name: Lancer les tests unitaires
        run: echo "Exécution des tests unitaires (utilise pytest ou autre si applicable)"

  build-and-publish:
    name: Livraison Continue
    needs: integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Connexion à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build et push de l'image Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mon-app:latest

      - name: Afficher le digest de l’image
        run: echo "Digest: ${{ steps.build-and-publish.outputs.digest }}"
